name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Build and zip binaries
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: |
            dist/linux-amd64/git-path-from-url.zip
            dist/linux-arm64/git-path-from-url.zip
            dist/darwin-amd64/git-path-from-url.zip
            dist/darwin-arm64/git-path-from-url.zip
            dist/windows-amd64/git-path-from-url.zip
            dist/windows-arm64/git-path-from-url.zip

