name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Build and zip binaries
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: |
            dist/git-path-from-url-linux-amd64.zip
            dist/git-path-from-url-linux-arm64.zip
            dist/git-path-from-url-darwin-amd64.zip
            dist/git-path-from-url-darwin-arm64.zip
            dist/git-path-from-url-windows-amd64.zip
            dist/git-path-from-url-windows-arm64.zip
